import React, { useState } from 'react';
import { 
  ArrowLeft, 
  CheckSquare, 
  Flag, 
  FileText, 
  Download, 
  ShieldAlert, 
  CheckCircle2, 
  Clock, 
  Cpu 
} from 'lucide-react';

export default function AnalysisResults({ 
  result, 
  onBack, 
  onToggleReviewed, 
  onToggleFlagged,
  onCorrect,
  user
}) {
  const [hoveredBox, setHoveredBox] = useState(false);
  const [completedActions, setCompletedActions] = useState({});
  const [isCorrecting, setIsCorrecting] = useState(false);
  
  const getInitialClass = () => {
    const title = (result.title || '').toLowerCase();
    if (title.includes('healthy')) return 'healthy';
    if (title.includes('soiling') || title.includes('pasting')) return 'dirty';
    if (title.includes('inflammation') || title.includes('erythema')) return 'inflamed';
    if (title.includes('prolapse')) return 'prolapse';
    return 'healthy';
  };
  
  const [correctedClass, setCorrectedClass] = useState(getInitialClass);

  if (!result) return null;

  const box = result.box || [38, 36, 24, 22];

  const handleSubmitCorrection = async () => {
    try {
      const response = await fetch(`/api/history/${result.id}/correct`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ correctedStatus: correctedClass })
      });
      
      if (!response.ok) {
        throw new Error(`Correction API returned status ${response.status}`);
      }
      
      const data = await response.json();
      const mergedResult = {
        ...result,
        status: data.correctedStatus,
        title: data.title,
        findings: data.findings,
        actions: data.actions
      };
      
      setIsCorrecting(false);
      if (onCorrect) {
        onCorrect(mergedResult);
      }
    } catch (e) {
      console.error(e);
      alert(`Failed to submit label correction: ${e.message}`);
    }
  };

  const handleActionToggle = (index) => {
    setCompletedActions(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  const getRiskColor = (status) => {
    switch (status) {
      case 'danger': return 'var(--danger-color)';
      case 'warning': return 'var(--warning-color)';
      default: return 'var(--healthy-color)';
    }
  };

  const downloadReport = () => {
    // Generate text/csv report as a file download
    const reportText = `
=============================================
CLOACASCAN AI DIAGNOSTIC REPORT
=============================================
Case ID: ${result.id}
Date: ${result.date} @ ${result.time}
Operator: ${user ? user.name : 'N/A'}
Farm: ${user ? user.farmName : 'N/A'}
---------------------------------------------
SCREENING RESULT: ${result.status.toUpperCase()}
Confidence Score: ${result.confidence}%
Model Version: ${result.modelVersion}
Analysis Time: ${result.analysisTime}
---------------------------------------------
DETAILED FINDINGS:
${result.findings.map((f, i) => `${i + 1}. ${f}`).join('\n')}

RECOMMENDED VETERINARY ACTION ITEMS:
${result.actions.map((a, i) => `${i + 1}. ${a} [${completedActions[i] ? 'COMPLETED' : 'PENDING'}]`).join('\n')}
=============================================
Generated by CloacaScan AI Diagnostic System.
    `;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `CloacaScan_Report_${result.id}.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Bounding box tooltip details based on status
  const getTooltipContent = () => {
    if (result.status === 'healthy') {
      return 'Healthy Cloacal opening: Tissue color rose-pink, zero feces pasting, skin integrity 100%.';
    }
    if (result.status === 'warning') {
      return 'Warning Cloacal area: Minor pasted uric crystals, local erythema (redness index 62%).';
    }
    return 'DANGER AREA: Pastey Vent discharge detected. Sphincter inflammation index 89%, severe fecal/exudate build up.';
  };

  return (
    <div className="page-container">
      {/* Back navigation */}
      <button 
        onClick={onBack} 
        className="btn btn-outline"
        style={{ marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '6px' }}
      >
        <ArrowLeft size={16} />
        Back to Dashboard / Upload
      </button>

      <div className="analysis-results-grid">
        {/* Left Side: Analyzed Image with Bounding Box */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          <div className="panel" style={{ padding: '16px' }}>
            <h3 style={{ fontSize: '15px', fontWeight: 600, marginBottom: '12px', color: 'var(--text-secondary)' }}>
              Neural Network Detection Frame
            </h3>

            <div className="preview-image-wrapper" style={{ margin: 0 }}>
              <img src={result.image} alt="Analyzed chicken vent" className="preview-image" />
              
              {/* SVG interactive bounding box overlay */}
              <svg 
                className="analysis-svg-overlay" 
                viewBox="0 0 100 100" 
                preserveAspectRatio="none"
              >
                <rect 
                  x={box[0]} 
                  y={box[1]} 
                  width={box[2]} 
                  height={box[3]} 
                  rx="3"
                  className={`bounding-box ${result.status}`}
                  strokeWidth="0.8"
                  style={{ pointerEvents: 'auto', cursor: 'help' }}
                  onMouseEnter={() => setHoveredBox(true)}
                  onMouseLeave={() => setHoveredBox(false)}
                />
              </svg>

              {/* Box Info Tooltip */}
              {hoveredBox && (
                <div 
                  className="bounding-box-tooltip"
                  style={{
                    position: 'absolute',
                    top: `${Math.min(80, box[1] + box[3] + 2)}%`,
                    left: '50%',
                    transform: 'translateX(-50%)',
                    width: '90%',
                    maxWidth: '280px',
                    whiteSpace: 'normal',
                    textAlign: 'center',
                    fontSize: '11px',
                    lineHeight: '1.4',
                    border: `1px solid ${getRiskColor(result.status)}`
                  }}
                >
                  {getTooltipContent()}
                </div>
              )}
            </div>
            
            <p style={{ fontSize: '11px', color: 'var(--text-tertiary)', marginTop: '8px', textAlign: 'center' }}>
              Hover cursor over the highlighted bounding box area to view localized anatomical observations.
            </p>
          </div>

          {/* Model Statistics Panel */}
          <div className="panel" style={{ display: 'flex', justifyContent: 'space-around', padding: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Cpu size={18} className="text-secondary" style={{ color: 'var(--text-secondary)' }} />
              <div style={{ display: 'flex', flexDirection: 'column' }}>
                <span style={{ fontSize: '10px', color: 'var(--text-tertiary)', textTransform: 'uppercase' }}>Model Core</span>
                <span style={{ fontSize: '13px', fontWeight: 600 }}>{result.modelVersion}</span>
              </div>
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Clock size={18} className="text-secondary" style={{ color: 'var(--text-secondary)' }} />
              <div style={{ display: 'flex', flexDirection: 'column' }}>
                <span style={{ fontSize: '10px', color: 'var(--text-tertiary)', textTransform: 'uppercase' }}>Inference Duration</span>
                <span style={{ fontSize: '13px', fontWeight: 600 }}>{result.analysisTime}</span>
              </div>
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <CheckCircle2 size={18} className="text-secondary" style={{ color: 'var(--text-secondary)' }} />
              <div style={{ display: 'flex', flexDirection: 'column' }}>
                <span style={{ fontSize: '10px', color: 'var(--text-tertiary)', textTransform: 'uppercase' }}>Fidelity Level</span>
                <span style={{ fontSize: '13px', fontWeight: 600 }}>High Confidence</span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Side: Diagnostics & Veterinary Action Plan */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          
          {/* Diagnostics Panel */}
          <div className="panel">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '14px' }}>
              <div>
                <span style={{ fontSize: '11px', color: 'var(--text-tertiary)', textTransform: 'uppercase', fontWeight: 600 }}>
                  Case Log: {result.id}
                </span>
                <h3 style={{ fontSize: '18px', fontWeight: 700, marginTop: '2px' }}>{result.title}</h3>
              </div>
              <span className={`status-badge ${result.status}`}>
                {result.status === 'healthy' ? 'Healthy' : result.status === 'warning' ? 'Warning' : 'Salmonella Risk'}
              </span>
            </div>

            <div style={{
              display: 'flex',
              alignItems: 'center',
              backgroundColor: 'var(--bg-secondary)',
              border: '1px solid var(--border-color)',
              borderRadius: 'var(--radius-md)',
              padding: '16px',
              marginBottom: '20px'
            }}>
              <div style={{ flex: 1 }}>
                <span style={{ fontSize: '12px', color: 'var(--text-secondary)', display: 'block' }}>
                  Risk Detection Confidence
                </span>
                <span style={{ fontSize: '32px', fontFamily: 'var(--font-display)', fontWeight: 800, color: getRiskColor(result.status) }}>
                  {result.confidence}%
                </span>
              </div>
              <div style={{ textAlign: 'right', fontSize: '12px', color: 'var(--text-secondary)' }}>
                <div>Screened: {result.date}</div>
                <div>Time: {result.time}</div>
              </div>
            </div>

            {/* Findings list */}
            <div>
              <h4 style={{ fontSize: '14px', fontWeight: 600, color: 'var(--text-primary)' }}>AI Diagnostic Observations</h4>
              <ul className="findings-list">
                {result.findings.map((f, i) => (
                  <li key={i} className="finding-item">
                    <div style={{
                      width: '6px',
                      height: '6px',
                      borderRadius: '50%',
                      backgroundColor: getRiskColor(result.status),
                      marginTop: '6px',
                      flexShrink: 0
                    }} />
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Action Checklist Panel */}
          <div className="panel">
            <h3 className="panel-title" style={{ marginBottom: '4px' }}>Veterinary Standard Operating Procedure</h3>
            <p style={{ fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '16px' }}>
              Operators should follow the following actions list. Mark items as completed for farm records.
            </p>

            <div className="action-checkbox-list">
              {result.actions.map((act, idx) => (
                <div 
                  key={idx} 
                  className={`action-checkbox-item ${completedActions[idx] ? 'checked' : ''}`}
                  onClick={() => handleActionToggle(idx)}
                >
                  <input 
                    type="checkbox" 
                    checked={!!completedActions[idx]} 
                    onChange={() => {}} 
                  />
                  <span>{act}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Record Actions / Review Panel */}
          <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <h3 className="panel-title">Diagnostic Record Management</h3>
            
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
              <button 
                onClick={() => onToggleReviewed(result.id)}
                className={`btn ${result.reviewed ? 'btn-primary' : 'btn-outline'}`}
                style={{
                  borderColor: result.reviewed ? '' : 'var(--healthy-color)',
                  color: result.reviewed ? '' : 'var(--healthy-color)',
                  backgroundColor: result.reviewed ? 'var(--healthy-color)' : '',
                }}
              >
                <CheckSquare size={16} />
                {result.reviewed ? 'Reviewed ✓' : 'Mark Reviewed'}
              </button>

              <button 
                onClick={() => onToggleFlagged(result.id)}
                className={`btn ${result.flagged ? 'btn-danger' : 'btn-outline'}`}
                style={{
                  borderColor: result.flagged ? '' : 'var(--warning-color)',
                  color: result.flagged ? '' : 'var(--warning-color)',
                  backgroundColor: result.flagged ? 'var(--warning-color)' : '',
                }}
              >
                <Flag size={16} />
                {result.flagged ? 'Flagged for Vet' : 'Flag for Vet'}
              </button>
            </div>

            <button 
              onClick={downloadReport} 
              className="btn btn-secondary btn-block"
              style={{ marginTop: '4px', padding: '12px' }}
            >
              <Download size={16} />
              Export Full Report (TXT)
            </button>
          </div>

          {/* Active Learning Feedback loop */}
          <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <h3 className="panel-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <ShieldAlert size={16} className="text-primary" style={{ color: 'var(--primary-color)' }} />
              Is this AI Diagnosis Correct?
            </h3>
            <p style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
              Discovered a mistake? Correct the class below to update records and help the AI retrain itself.
            </p>
            
            {!isCorrecting ? (
              <button 
                onClick={() => setIsCorrecting(true)} 
                className="btn btn-outline btn-block"
                style={{ padding: '10px' }}
              >
                No, Correct Diagnosis
              </button>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                <select 
                  className="form-select"
                  value={correctedClass}
                  onChange={(e) => setCorrectedClass(e.target.value)}
                  style={{ padding: '10px', fontSize: '13px' }}
                >
                  <option value="healthy">Healthy</option>
                  <option value="dirty">Dirty / Soiled Feathers</option>
                  <option value="inflamed">Inflamed Cloaca</option>
                  <option value="prolapse">Prolapsed Vent</option>
                </select>
                
                <div style={{ display: 'flex', gap: '10px' }}>
                  <button 
                    onClick={handleSubmitCorrection}
                    className="btn btn-primary"
                    style={{ flex: 1, padding: '10px', fontSize: '13px' }}
                  >
                    Submit Correction
                  </button>
                  <button 
                    onClick={() => setIsCorrecting(false)}
                    className="btn btn-secondary"
                    style={{ padding: '10px', fontSize: '13px' }}
                  >
                    Cancel
                  </button>
                </div>
              </div>
            )}
          </div>

        </div>
      </div>
    </div>
  );
}
